export const EMAIL_INVALID = 'EMAIL_INVALID';
export const TOKEN_INVALID = 'TOKEN_INVALID';
export const USER_ALREADY_REGISTER = 'USER_ALREADY_REGISTER';
export const USER_NEED_CONFIRM_EMAIL = 'USER_NEED_CONFIRM_EMAIL';
export const SUCCESS = 'SUCCESS';
